/**
 * Site-wide SEO primitives: identity, URL building and JSON-LD.
 *
 * Everything a crawler needs that isn't page copy lives here so the individual
 * routes stay about layout. Two rules hold across the file:
 *
 *  1. Anything a crawler or a social scraper reads must be an *absolute* URL.
 *     Relative paths work for a human clicking a link and fail for everyone
 *     else, so `absoluteUrl` is the only way a URL leaves this module.
 *  2. Structured data must describe what is actually on the page. Marking up
 *     a headline that isn't rendered is what earns a manual action, so every
 *     builder below takes the same values the JSX does.
 */

import type { ApiArticle, ApiArticleImage, ApiArticleListItem, ApiCategory } from './api';
import { coverOf, excerptOf, mediaUrl } from './api';
import { stripHtml } from './sanitize';

/** Canonical origin of the public site. No trailing slash. */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000'
).replace(/\/+$/, '');

export const SITE = {
  name: 'Celeb Scoop',
  /** Used in `<title>` templates and the Organization node. */
  legalName: 'Celeb Scoop',
  tagline: 'Entertainment & Celebrity News',
  description:
    'Breaking entertainment news, red carpet galleries, exclusive interviews and celebrity culture — reported daily by the Celeb Scoop newsroom.',
  locale: 'en_US',
  lang: 'en',
  twitter: '@celebscoop',
  /** Fallback social card — generated by `app/og/route.tsx`. */
  ogImage: '/og',
} as const;

/** Resolve any path or already-absolute URL against the canonical origin. */
export function absoluteUrl(path = '/'): string {
  if (/^https?:\/\//i.test(path)) return path;
  return `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
}

/** The social card for an article, falling back to the site default. */
export function socialImage(article?: {
  images?: ApiArticleImage[];
  cover_image_url?: string | null;
}): string {
  // `coverOf` already resolves the media path; only the origin is missing.
  const cover = article ? coverOf(article) : null;
  return cover ? absoluteUrl(cover) : absoluteUrl(SITE.ogImage);
}

/**
 * When a story was last genuinely edited.
 *
 * The API bumps `updated_at` on a real edit only — a page view leaves it
 * alone — so it is safe to publish as `dateModified` and as a sitemap
 * `lastmod`. Both are trust-scored: a timestamp that moves without the page
 * moving teaches Google to ignore it, so nothing here may depend on when the
 * value happened to be read.
 *
 * Clamped to `created_at` because a modified date *earlier* than publication
 * is a structured-data validation error, and an unedited story can carry an
 * `updated_at` a hair behind its own `created_at`.
 */
export function lastModified(article: {
  created_at: string;
  updated_at?: string | null;
}): Date {
  const published = new Date(article.created_at);
  const modified = article.updated_at ? new Date(article.updated_at) : null;
  if (!modified || Number.isNaN(modified.getTime()) || modified < published) {
    return published;
  }
  return modified;
}

/**
 * Serialise a JSON-LD graph for `dangerouslySetInnerHTML`.
 *
 * `</script>` inside a string value would close the tag early and drop the rest
 * of the document into the page as markup, so `<` is escaped on the way out.
 */
export function jsonLd(data: unknown): { __html: string } {
  return { __html: JSON.stringify(data).replace(/</g, '\\u003c') };
}

// ── Graph builders ────────────────────────────────────────────────────────────

/** Stable @id for the publisher node, so other nodes can reference it. */
const ORG_ID = `${SITE_URL}/#organization`;
const SITE_ID = `${SITE_URL}/#website`;

export function organizationSchema() {
  return {
    '@type': 'NewsMediaOrganization',
    '@id': ORG_ID,
    name: SITE.name,
    legalName: SITE.legalName,
    url: absoluteUrl('/'),
    description: SITE.description,
    logo: {
      '@type': 'ImageObject',
      url: absoluteUrl('/icon.svg'),
      width: 512,
      height: 512,
    },
  };
}

/**
 * The site node, including the search action that lets Google render a
 * sitelinks search box pointed at our own results page.
 */
export function websiteSchema() {
  return {
    '@type': 'WebSite',
    '@id': SITE_ID,
    url: absoluteUrl('/'),
    name: SITE.name,
    description: SITE.description,
    inLanguage: SITE.lang,
    publisher: { '@id': ORG_ID },
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${absoluteUrl('/search')}?q={search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
  };
}

/** Wrap nodes in a single `@graph` so one script tag carries the whole page. */
export function graph(...nodes: unknown[]) {
  return { '@context': 'https://schema.org', '@graph': nodes.filter(Boolean) };
}

export type Crumb = { name: string; path: string };

/**
 * Breadcrumbs for the result snippet. The trail must match the visible one —
 * the pages below render the same array they pass in here.
 */
export function breadcrumbSchema(crumbs: Crumb[]) {
  return {
    '@type': 'BreadcrumbList',
    '@id': `${absoluteUrl(crumbs[crumbs.length - 1]?.path ?? '/')}#breadcrumb`,
    itemListElement: crumbs.map((crumb, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}

/**
 * A `NewsArticle` node — the type Google Top Stories keys off.
 *
 * `dateModified` comes from `lastModified`, so an unedited story reports its
 * publication date rather than the moment a crawler happened to load it.
 */
export function newsArticleSchema(
  article: ApiArticle,
  options: { categoryName: string; categorySlug: string | null; wordCount: number }
) {
  const url = absoluteUrl(`/article/${article.slug}`);
  const published = new Date(article.created_at);
  const images = (article.images ?? [])
    .slice()
    .sort((a, b) => a.sort_order - b.sort_order)
    .map((image) => absoluteUrl(mediaUrl(image.image_url)));
  const cover = coverOf(article);
  const coverUrl = cover ? absoluteUrl(cover) : null;
  if (coverUrl && !images.includes(coverUrl)) images.unshift(coverUrl);

  return {
    '@type': 'NewsArticle',
    '@id': `${url}#article`,
    isPartOf: { '@id': SITE_ID },
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    url,
    headline: article.title.slice(0, 110), // Google truncates past 110 chars.
    description: article.summary ?? excerptOf(article.content),
    articleSection: options.categoryName,
    inLanguage: SITE.lang,
    wordCount: options.wordCount,
    datePublished: published.toISOString(),
    dateModified: lastModified(article).toISOString(),
    image: images.length > 0 ? images : [absoluteUrl(SITE.ogImage)],
    author: {
      '@type': 'Organization',
      name: `${options.categoryName} Desk`,
      url: options.categorySlug
        ? absoluteUrl(`/category/${options.categorySlug}`)
        : absoluteUrl('/'),
    },
    publisher: { '@id': ORG_ID },
    isAccessibleForFree: true,
  };
}

/**
 * An ordered list of stories, for index pages (home, feed, category).
 *
 * Only URLs are emitted, not duplicated headlines: `ItemList` of bare URLs is
 * the shape Google documents for a list of separate pages, and it keeps the
 * markup honest when the card copy is truncated.
 */
export function itemListSchema(
  articles: ApiArticleListItem[],
  options: { path: string; name: string }
) {
  return {
    '@type': 'ItemList',
    '@id': `${absoluteUrl(options.path)}#list`,
    name: options.name,
    numberOfItems: articles.length,
    itemListOrder: 'https://schema.org/ItemListOrderDescending',
    itemListElement: articles.map((article, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      url: absoluteUrl(`/article/${article.slug}`),
      name: article.title,
    })),
  };
}

export function collectionPageSchema(category: ApiCategory) {
  const url = absoluteUrl(`/category/${category.slug}`);
  return {
    '@type': 'CollectionPage',
    '@id': `${url}#collection`,
    url,
    name: category.name,
    description: categoryDescription(category),
    isPartOf: { '@id': SITE_ID },
    inLanguage: SITE.lang,
  };
}

/** House copy for a section, used for both the meta tag and the graph node. */
export function categoryDescription(category: ApiCategory): string {
  return (
    category.description?.trim() ||
    `The latest ${category.name.toLowerCase()} news, photos and exclusives from the ${SITE.name} newsroom.`
  );
}

// ── Text helpers ──────────────────────────────────────────────────────────────

/**
 * Trim a description to something a search result will actually show.
 *
 * Google renders roughly 155–160 characters; anything past that is dead weight
 * that pushes the useful words out of the snippet.
 */
export function metaDescription(text: string | null | undefined, limit = 158): string {
  const clean = stripHtml(text ?? '').replace(/\s+/g, ' ').trim();
  if (!clean) return SITE.description;
  if (clean.length <= limit) return clean;
  const cut = clean.slice(0, limit);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > limit * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[,;:.\s]+$/, '')}…`;
}

/** Word count behind the markup, for `wordCount` and reading time. */
export function wordCount(content: string): number {
  return stripHtml(content).split(/\s+/).filter(Boolean).length;
}
