"""add_created_by_updated_by_audit_columns

Revision ID: 7f2f4a1fe17e
Revises: a1b2c3d4e5f6
Create Date: 2026-08-23 22:35:47.016001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2f4a1fe17e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_images', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('article_images', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('roles', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_by')
    op.drop_column('categories', 'updated_by')
    op.drop_column('categories', 'created_by')
    op.drop_column('articles', 'updated_by')
    op.drop_column('articles', 'created_by')
    op.drop_column('article_images', 'updated_by')
    op.drop_column('article_images', 'created_by')
    # ### end Alembic commands ###
